### ISSUE TITLE
Barra plugin issue

### ISSUE THREAD

**Issue by Labrat-alter** [Limbos-goodies-for-LCDSmartie/barra#1]
First of all big thank You for creating those big pack of plugins!

I have issue with barra plugin with displaying values
Video is attached. 
[2024-08-26 19-15-32.zip](https://github.com/user-attachments/files/16751708/2024-08-26.19-15-32.zip)

**Comment by limbo666** [comment]
I checked the video and i'm not sure what should I look for. Can you please elaborate on this?
What is the issue?

**Comment by Labrat-alter** [comment]
For $dll(barra,1,$dll(vol,1,2,),10)
value 52% is presented incorrectly ( 1 column of pixels in cell 5) should be 1 column in cell 6 
![obraz](https://github.com/user-attachments/assets/248e1447-df37-4991-8c57-e080cac93b3b)
for 50% is presented correctly as full (5 column of pixels in cell 5)
![obraz](https://github.com/user-attachments/assets/18ee51cf-dd88-48e6-ac5b-8a2acf25b9a9)
for 48% is presented incorrectly ( 4 columns of pixels in cell 4) should be 4 columns in cell 5
![obraz](https://github.com/user-attachments/assets/9f21338f-7a40-464c-b99f-70b4ebdb8add)


for values <10% there are 11 symbols presented 
![obraz](https://github.com/user-attachments/assets/e3e8a376-be97-426e-b8c4-0ecf2160d71f)

**Comment by limbo666** [comment]
OK I will dig to teh source code to see what is wrong there.
Thanks for pointing this out.

**Comment by limbo666** [comment]
Version 1.2 is ready [Barra.zip](https://github.com/user-attachments/files/16803772/Barra.zip)
This version is still buggy  but it calculates way better the blocks in a bar.
